import {
  ActivityIcon,
  AppleIcon,
  ArrowRightIcon,
  CheckIcon,
  ChevronDownIcon,
  FileTextIcon,
  FingerprintIcon,
  GiftIcon,
  GlobeIcon,
  HeartIcon,
  HomeIcon,
  KeyRoundIcon,
  LayersIcon,
  LockIcon,
  MenuIcon,
  MoonIcon,
  PlayIcon,
  QuoteIcon,
  ScaleIcon,
  ScrollTextIcon,
  ShieldCheckIcon,
  ShieldIcon,
  StarIcon,
  SunIcon,
  UsersIcon,
  XIcon,
  type LucideIcon,
} from "lucide-react"
import { type IconName } from "@workspace/landing-content"

/** Editor previews for the landing icon names. MUST mirror the MAP in
 *  apps/landing/src/components/Icon.astro (same keys as ICON_NAMES). */
export const ICON_COMPONENTS: Record<IconName, LucideIcon> = {
  pulse: ActivityIcon,
  apple: AppleIcon,
  arrowR: ArrowRightIcon,
  check: CheckIcon,
  chevD: ChevronDownIcon,
  doc: FileTextIcon,
  fingerprint: FingerprintIcon,
  gift: GiftIcon,
  globe: GlobeIcon,
  heart: HeartIcon,
  home: HomeIcon,
  key: KeyRoundIcon,
  layers: LayersIcon,
  lock: LockIcon,
  menu: MenuIcon,
  moon: MoonIcon,
  play: PlayIcon,
  quote: QuoteIcon,
  scales: ScaleIcon,
  scroll: ScrollTextIcon,
  shield: ShieldIcon,
  shieldCheck: ShieldCheckIcon,
  star: StarIcon,
  sun: SunIcon,
  users: UsersIcon,
  x: XIcon,
}
